---

- hosts: aws_ec2

   vars:
    ansible_user: ec2-user
    ansible_ssh_private_key_file: /home/ec2-user/environment/work/final project/keypair1.pem
    source_file: ./index.html
    dest_file: /var/www/html
   

  gather_facts: False

  tasks:
    - name: ping
      shell: ping -c 1 -w 2 8.8.8.8
      ignore_errors: true
    
